# Generated by Django 5.1.3 on 2024-12-17 13:26

import django.db.models.deletion
import django.utils.timezone
import family.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_adminuser_options_alter_adminuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengequestion',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='familychallenge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='familychallenge',
            name='family_group',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice')], default='multiple_choice', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', null=True ,to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=models.JSONField(), max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(default=['Berlin', 'Paris', 'Madrid', 'Rome']),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchallengeresults', to='family.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChallengeAnswer',
        ),
        migrations.DeleteModel(
            name='ChallengeQuestion',
        ),
        migrations.DeleteModel(
            name='FamilyChallenge',
        ),
    ]
