# Generated by Django 5.1.3 on 2024-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_remove_challengequestion_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='no choices provided', max_length=255),
        ),
    ]
