# Generated by Django 5.1.3 on 2024-12-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
